version: '3'

includes:
  snow-cli: ./tasks/snow-cli/snowcli-tasks.yml
  aws-cli: ./tasks/aws-cli/awscli-tasks.yml

env:
  ENV_DIR: .env
  TASKS_DIR: tasks

dotenv: ['{{ .ENV_DIR }}/{{ .DOTENV_FILENAME | default "demo.env" }}']

tasks:

  demo-up:
    desc: |
      Usage: `task demo-up` if using the default demo.env file. Use `DOTENV_FILENAME=custom.env task demo-up` 
      if using a custom .env file (filename does not have to be custom.env, but must end with .env).

    cmds:
      - task: snow-cli:sort-and-process-sql-folder
        vars:
          TASKS_DIR: $TASKS_DIR
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME
#      - task: aws:upload-artifacts-to-s3
#        vars:
#          TASKS_DIR: $TASKS_DIR
#          BUCKET_NAME_OR_S3_URI: $BUCKET_NAME_OR_S3_URI
#          S3_OPTIONAL_PREFIX: $S3_OPTIONAL_PREFIX
