version: '3'

includes:
  validate-prerequisites: ./tasks/validate-prerequisites/validate-prerequisite-tasks.yml
  snow-cli: ./tasks/snow-cli/snowcli-tasks.yml
  python: ./tasks/python/python-tasks.yml
  agent:
    taskfile: ./tasks/agent/create-agent/create-agent.yml
    dir: ./tasks/agent/create-agent

env:
  ENV_DIR: .env

dotenv: ['{{ .ENV_DIR }}/{{ .DOTENV_FILENAME | default "demo.env" }}']

tasks:

  python-setup-for-agents:
    desc: Setup Python environment with required packages for agent tasks.
    cmds:
      - task: python:create-venv
      - task: python:install-packages

  demo-up:
    desc: |
      Usage: `task demo-up` if using the default demo.env file. Use `DOTENV_FILENAME=custom.env task demo-up`
      if using a custom .env file (filename does not have to be custom.env, but must end with .env).

    cmds:
      - task: validate-prerequisites:snowcli
        silent: true

      - task: snow-cli:sort-and-process-sql-folder
        vars:
          SQL_SORT_PROCESS_DIR: ./tasks/snow-cli/sql/batch-1
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME

      - task: snow-cli:upload-files-to-internal-named-stage
        vars:
          FILE_UPLOAD_DIR: $FILE_UPLOAD_DIR
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME
          INTERNAL_NAMED_STAGE: $INTERNAL_NAMED_STAGE

      - task: snow-cli:sort-and-process-sql-folder
        vars:
          SQL_SORT_PROCESS_DIR: ./tasks/snow-cli/sql/batch-2
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME

#      - task: agent:create-agents-from-json-files
#        vars:
#          USER_PAT: $USER_PAT

      - task: snow-cli:deploy-streamlit-app
        vars:
          STREAMLIT_APP_DIR: $STREAMLIT_APP_DIR
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME

  demo-down:
    desc: |
      Usage: `task demo-down` will teardown the demo. In this case, dropping the database which is created as part of the demo.

    cmds:
      - task: snow-cli:drop-database-if-exists
        vars:
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME
          DATABASE_NAME: $DATABASE_NAME

  create-agent:
    desc: Creates agent from create_agent.json file.
    cmds:
      - task: agent:create-agent